-- MySQL Script generated by MySQL Workbench
-- Mon Jun 22 11:17:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `xd_divisions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_divisions` ;

CREATE TABLE IF NOT EXISTS `xd_divisions` (
  `div_code` INT NOT NULL,
  `division_name` VARCHAR(100) NULL,
  PRIMARY KEY (`div_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xd_employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_employees` ;

CREATE TABLE IF NOT EXISTS `xd_employees` (
  `e_id` INT NOT NULL AUTO_INCREMENT,
  `port` ENUM('C', 'G', 'T') NULL,
  `computer_number` VARCHAR(8) NULL,
  `initials` VARCHAR(45) NULL,
  `surname` VARCHAR(100) NULL,
  `payoffice` VARCHAR(6) CHARACTER SET 'ascii' NULL,
  `service_number` VARCHAR(20) NULL,
  `nic` VARCHAR(20) NULL,
  `dob` DATE NULL,
  `division_code` INT NOT NULL,
  `balance_opd_amount` DOUBLE NULL DEFAULT 10000,
  `balance_specs_amount` DOUBLE NULL DEFAULT 10000,
  PRIMARY KEY (`e_id`),
  INDEX `fk_xd_employees_xd_divisions1_idx` (`division_code` ASC) VISIBLE,
  CONSTRAINT `fk_xd_employees_xd_divisions1`
    FOREIGN KEY (`division_code`)
    REFERENCES `xd_divisions` (`div_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xd_dependants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_dependants` ;

CREATE TABLE IF NOT EXISTS `xd_dependants` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `relationship` ENUM('SPOUSE', 'CHILD', 'MOTHER', 'FATHER') NULL,
  `full_name` VARCHAR(200) NULL,
  `nic` VARCHAR(20) NULL,
  `xd_employees_e_id` INT NOT NULL,
  `dob` DATE NULL,
  `document_received` INT NULL,
  PRIMARY KEY (`d_id`),
  INDEX `fk_xd_dependants_xd_employees_idx` (`xd_employees_e_id` ASC) VISIBLE,
  CONSTRAINT `fk_xd_dependants_xd_employees`
    FOREIGN KEY (`xd_employees_e_id`)
    REFERENCES `xd_employees` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xsu_system_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xsu_system_users` ;

CREATE TABLE IF NOT EXISTS `xsu_system_users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(200) NULL,
  `username` VARCHAR(45) NULL,
  `paswd` VARCHAR(100) NULL,
  `status` INT NULL DEFAULT 1,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xd_claim_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_claim_requests` ;

CREATE TABLE IF NOT EXISTS `xd_claim_requests` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(20) NULL,
  `opd_date` DATE NULL,
  `amount_requested` DOUBLE NULL,
  `claim_type` ENUM('opd', 'specs') NULL,
  `patient_name` VARCHAR(100) NULL,
  `emp_computer_number` VARCHAR(20) NULL,
  `is_ducument_received` INT NULL DEFAULT 0,
  `document_received_date` DATETIME NULL,
  `invoice_number` VARCHAR(45) NULL,
  `medical_recommendation` VARCHAR(45) NULL,
  `medical_remark` VARCHAR(45) NULL,
  `doctor_approved_date` DATE NULL,
  `approved_amount` DOUBLE NULL,
  `payment_approved_date` DATE NULL,
  `paid_date` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `claim_for` ENUM('MYSELF', 'SPOUSE', 'CHILD', 'MOTHER', 'FATHER') NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xd_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_statuses` ;

CREATE TABLE IF NOT EXISTS `xd_statuses` (
  `s_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NULL,
  `status_order` INT NULL,
  PRIMARY KEY (`s_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xd_claim_history_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xd_claim_history_log` ;

CREATE TABLE IF NOT EXISTS `xd_claim_history_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `remarks` VARCHAR(45) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `claim_requests_id` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `old_status_id` INT NOT NULL,
  `new_status_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_xd_claim_history_log_xd_claim_requests1_idx` (`claim_requests_id` ASC) VISIBLE,
  INDEX `fk_xd_claim_history_log_xsu_system_users1_idx` (`updated_by` ASC) VISIBLE,
  INDEX `fk_xd_claim_history_log_xd_statuses1_idx` (`old_status_id` ASC) VISIBLE,
  INDEX `fk_xd_claim_history_log_xd_statuses2_idx` (`new_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_xd_claim_history_log_xd_claim_requests1`
    FOREIGN KEY (`claim_requests_id`)
    REFERENCES `xd_claim_requests` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_xd_claim_history_log_xsu_system_users1`
    FOREIGN KEY (`updated_by`)
    REFERENCES `xsu_system_users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_xd_claim_history_log_xd_statuses1`
    FOREIGN KEY (`old_status_id`)
    REFERENCES `xd_statuses` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_xd_claim_history_log_xd_statuses2`
    FOREIGN KEY (`new_status_id`)
    REFERENCES `xd_statuses` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
